// cspell.config.js

/** @type {import('cspell').CSpellUserSettings} */
module.exports = {
  version: '0.2',
  language: 'en',
  words: [
    // Project-specific terms
    'lorebound',
    'lorebounds',
    'luxury',
    'nobility',
    'pathways',
    'supabase',
    'Nextjs',
    'Josefin',
    'RingofKerry',
    'Orbitron',
    'Cinzel',
    'mp3',
    'favicon',
    'authguard',
    'unwarn',
    'unmute',
    'Nav',
    'OAuth',
    'pathname',
    'Leaderboard',
    'Nexus',
    'anime',
    'manga',
    'Otaku',
    'lore',
    'asyncable',
    'glassmorphism',

    // Tech terms
    'jsx',
    'tailwindcss',
    'zindex',
    'auth',
    'utils',
    'nodejs',
    'vercel',
    'eslint',
    'postcss',
    'prettier',
    'vite',
    'vitejs',
    'api',
    'webhooks',
    'json',
    'config',

    // UI-specific
    'Superbutton',
    'Glasscard',
    'Pathwaynav',
    'Noblecursor',
    'luxglass',
    'luxnav',
    'hoverable',
    'cardgrid',
    'searchbar',
    ''
  ],
  ignorePaths: [
    '**/node_modules/**',
    '**/.next/**',
    '**/dist/**',
    '**/build/**',
    '**/public/**',
    '**/coverage/**',
    '**/*.lock',
    '**/*.mp3',
    '**/*.mp4',
    '**/*.ico',
    '**/*.png',
    '**/*.jpg',
    '**/*.jpeg',
    '**/*.webp',
  ],
  dictionaries: ['typescript', 'node', 'softwareTerms', 'html', 'css', 'filetypes', 'fonts'],
  enableFiletypes: ['.js', '.jsx', '.ts', '.tsx', '.css', '.scss', '.md'],
  ignoreWords: ['TODO', 'FIXME'],
};
